name: DiscordBridge
version: 0.0.4
description: Bridges the gap between Discord and Minecraft
author: IntriguingTiles
website: https://github.com/IntriguingTiles/DiscordBridge
softdepend: [FactionChat]
main: xyz.hgrunt.discordbridge.Minecraft

commands:
   discordbridge:
      description: Reloads the config
      permission: discordbridge.reload